# Generated by Django 3.0 on 2020-04-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcements_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
