# Generated by Django 3.0 on 2020-05-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.CharField(max_length=3000, verbose_name='Your Bio'),
        ),
    ]
